pipeline {
    agent any
    stages {
        stage('Delete ex containers') {
            steps {
                echo 'Delete ex containers'
                sh '''
                docker stop hello-world-container
                docker rm hello-world-container
                docker image prune -af
                '''
            }
        }
        stage('Build App Docker Image') {
            steps {
                echo 'Building App Image'
                sh '''
                docker build --force-rm -t "hello-world-app" "${WORKSPACE}/tasks/docker-hello-world-app/app"
                docker image ls
                '''
            }
        }
        stage('Deploy App'){
            steps {
                echo 'Deploying App'
                sh '''
                docker run -d --name hello-world-container -p 80:80 hello-world-app
                docker ps -a
                '''
            }
        }
    }
    post {
        always {
            echo 'Deleting all local images'
            sh 'docker image prune -af'
        }
    }
}